name: Container Workflow
on: workflow_dispatch

env:
  ACR_LOGIN_SERVER: aistraining.azurecr.io
  TAG_NAME: eshoponweb-prissana:1.0.0
  IMAGE_NAME: ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.TAG_NAME }}
  RESOURCE_GROUP: rg-eshop-018
  CLUSTER_NAME: aks-eshop-018
  
jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkput source code
        uses: actions/checkout@v7.0.0

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-vserver: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD}}

      - name: Build and Push Image
        run: |
          docker build -f src/Web/Dockerfile -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }} .
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}
  deploy-to-aks:
    needs: build-container
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7.0.0
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            .k8s/services.yaml
            .k8s/deployment.yaml
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}
       
