name: Container Workflow

on:
  workflow_dispatch:
    inputs:
      dockerfile-choice:
        description: 'เลือก Dockerfile ที่ต้องการ Build'
        required: true
        default: 'src/Web/Dockerfile'
        type: choice
        options:
          - src/Web/Dockerfile
          - src/PublicApi/Dockerfile

env:
  ACR_LOGIN_SERVER: aistraining.azurecr.io
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  TAG_NAME: eshoponweb-019
  IMAGE_VERSION: 1.0.0
  AZURE_AKS_CLUSTER: aks-demo
  AZURE_RESOURCE_GROUP: ais-training

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: ACR Login
        uses: azure/docker-login@v2 
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile-choice }}
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{env.TAG_NAME}}${{ inputs.dockerfile-choice == 'src/Web/Dockerfile' && 'webapp' || 'publicapi' }}:${{ env.IMAGE_VERSION }}

  deploy-to-aks:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: AKS Set Context
        uses: azure/aks-set-context@v2
        with:
          cluster-name: ${{ env.AZURE_AKS_CLUSTER }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}

      - name: K8s Deployment
        uses: azure/k8s-deploy@v4
        with:
          namespace: eshoponweb-prissana
          manifests: |
            .k8s/deployment.yaml
            .k8s/services.yaml
          image: ${{ env.ACR_LOGIN_SERVER }}/${{env.TAG_NAME}}${{ inputs.dockerfile-choice == 'src/Web/Dockerfile' && 'webapp' || 'publicapi' }}:${{ env.IMAGE_VERSION }}